import {test} from 'node:test';
import assert from 'node:assert/strict';
import {generate,initial,step} from '../evals/courier-grid/src/simulation.js';
function state(){const scenario=generate(42);scenario.start={x:2,y:2};scenario.enemies=[];scenario.jobs=[{id:'p0',from:{x:2,y:2},to:{x:3,y:2},value:10,weight:3,deadline:20,status:'available'},{id:'p1',from:{x:2,y:2},to:{x:4,y:2},value:5,weight:2,deadline:20,status:'available'}];return initial(scenario);}
test('cargo weight affects movement energy, delivery retains earned value',()=>{const s=state();step(s,{type:'pickup',id:'p0'});step(s,{type:'pickup',id:'p1'});step(s,{type:'move',dir:'E'});assert.equal(s.courier.battery,88);step(s,{type:'deliver'});assert.equal(s.value,10);step(s,{type:'move',dir:'E'});assert.equal(s.courier.battery,87);step(s,{type:'deliver'});assert.equal(s.value,15);assert.equal(s.status,'complete');});
test('invalid actions spend ticks and deadlines expire carried parcels',()=>{const s=state();s.jobs[0].deadline=1;step(s,{type:'pickup',id:'p0'});step(s,{type:'charge'});assert.equal(s.jobs[0].status,'expired');assert.deepEqual(s.courier.cargo,[]);step(s,{type:'pickup',id:'missing'});assert.equal(s.tick,3);assert.equal(s.invalid,1);});
test('delivery exactly on the deadline counts',()=>{const s=state();s.jobs[0].deadline=2;step(s,{type:'pickup',id:'p0'});step(s,{type:'move',dir:'E'});step(s,{type:'deliver'});assert.equal(s.value,10);assert.equal(s.jobs[0].status,'delivered');});
test('entering an enemy occupied cell captures even if it moves away',()=>{const s=state();s.enemies=[{id:'patrol',kind:'patrol',x:3,y:2,period:3,waypoints:[{x:4,y:2}],waypoint:0,target:null}];step(s,{type:'move',dir:'E'});assert.equal(s.enemies[0].x,4);assert.equal(s.status,'captured');});
test('zero battery is recoverable at a charger but ends a run elsewhere',()=>{const s=state();s.courier.battery=0;step(s,{type:'charge'});assert.equal(s.courier.battery,18);assert.equal(s.status,'active');s.courier.battery=1;step(s,{type:'move',dir:'E'});assert.equal(s.status,'exhausted');});
